name: carboneye
description: Real-time deforestation monitoring.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  http: ^1.2.1
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.2
  model_viewer_plus: ^1.7.0 
  flutter_map_heatmap: ^0.0.8
  flutter_local_notifications: ^17.1.2
  path_provider: ^2.1.3
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  
dev_dependencies:
  flutter_launcher_icons: ^0.14.4

  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
    android: true
    ios: true
    image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/satellite_forest.png
    - assets/icons/app_icon.png
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
